<?khml version='1.0' encoding='UTF-8'?>
<paperweb> 
  <page id="syntax-highlight.sh" type="script">
    <title>Syntax Highlighting Script for CGit</title>
    <author>Seriki Yakub</author>
    <date>2 Dec, 2025</date>
    <description>
      This shell script implements syntax highlighting in the cgit tree-view
      by calling the 'highlight' command for different file extensions.
      It supports multiple highlight versions (2, 3) and maps extensions like
      Makefile, *.c, *.py, etc.
    </description>
    <code language="bash">
      <![CDATA[
bin/sh
# This script can be used to implement syntax highlighting in the cgit
# tree-view by referring to this file with the source-filter or repo.source-
# filter options in cgitrc.
#
# This script requires a shell supporting the ${var##pattern} syntax.
# It is supported by at least dash and bash, however busybox environments
# might have to use an external call to sed instead.
# 
# Note: the highlight command (http://www.andre-simon.de/) uses css for syntax
# highlighting, so you'll probably want something like the following included
# in your css file:
#
# Style definition file generated by highlight 2.4.8, http://www.andre-simon.de/
# ...
# (full comments truncated for brevity)
# ...

# store filename and extension in local vars
BASENAME="$1"
EXTENSION="${BASENAME##*.}"

[ "${BASENAME}" = "${EXTENSION}" ] && EXTENSION=txt
[ -z "${EXTENSION}" ] && EXTENSION=txt

# map Makefile and Makefile.* to .mk
[ "${BASENAME%%.*}" = "Makefile" ] && EXTENSION=mk

# highlight versions 2 and 3 have different commandline options.
#
# Version 2 can be found (for example) on EPEL 5, while version 3 can be
# found (for example) on EPEL 6.
#
# This is for version 2
exec highlight --force -f -I -X -S "$EXTENSION" 2>/dev/null

# This is for version 3
#exec highlight --force -f -I -O xhtml -S "$EXTENSION" 2>/dev/null
      ]]>
    </code>
    <tags>bash, highlight, syntax, cgit, script</tags>
    <references>
      <ref url="http://www.andre-simon.de/" description="Highlight Command"/>
    </references>
  </page>
</paperweb>
